# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeedReporter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeedReporter
  pod 'MSCircularSlider'
  pod 'Alamofire'
  pod "MTCircularSlider"

  target 'SpeedReporterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpeedReporterUITests' do
    # Pods for testing
  end

end
